###############################################################################
# SPECtools2000
#   Version 0.3
#   This makefile should NOT be changed other than to customize for a 
#   particular benchmark.  Users may overide variables by placing them
#   in the Makefile.spec file.  Or by using the "runspec" program to 
#   build the Makefile.spec file for them.
###############################################################################
#	BENCHMARK	-- standard definitions for this benchmark

NUMBER    = 200
NAME      = sixtrack
EXEBASE   = sixtrack
BENCHLANG = F77
SOURCES   = abend.f adia.f adib.f ambm6.f analie6.f betalf.f block.f \
	    blockdis.f caconv.f calrms.f chroma.f cinvar.f clor6.f \
	    clorb.f clorb2.f combel.f comnul.f corrorb.f cpart6.f \
	    cphase.f cpltwis.f creat6.f ctrbasi6.f dacond6.f dacopd6.f \
	    dalie6s.f dalind6.f daprid6.f daten.f decoup.f detune.f \
	    dinv.f dist1.f distance.f dlie6.f eig66.f envada.f envar.f \
	    envardis.f envars.f envarsv.f envquad.f errf.f errff.f \
	    error.f fexpo6.f fft.f fit.f flush.f forest6.f foxys.f \
	    gam6.f gbm6.f gofix6.f hbook.f htal.f htbl.f htls.f htrl.f \
	    htul.f hyper6.f igmeta.f intd6.f intepr.f join.f lie6.f \
	    linopt.f loesd.f lostpar2.f lostpar3.f lostpart.f maincr.f \
	    mainia6.f matrix.f maxmin.f midbloc6.f mul66.f mywwerf.f \
	    orbinit.f ord.f orderma6.f phasad.f postpr.f putorb.f \
	    qmod.f ranecu.f resb6.f resex.f resl6.f rext6.f ripple.f \
	    rmod.f rotatio6.f search.f sinpro.f sixdaco6.f subre.f \
	    subsea.f sumpos.f synoda.f synuthck.f take6.f taked6.f \
	    thck4d.f thck6d.f thck6dua.f thin4d.f thin6d.f thin6dua.f \
	    trauthck.f trauthin.f trx6.f tuer6.f umlau6.f umlauf.f \
	    write4.f write6.f writebin.f writelin.f wzset.f wzsubf.f \
	    wzsubv.f xuflow.f

# Include standard template for this suite
-include ../../../../Makefile.defaults
-include ../../../Makefile.defaults
-include ../../Makefile.defaults
-include ../Makefile.defaults

nomakefiles:
	@echo "*** Whoops!  I didn't find a Makefile.defaults file."
	@echo "*** Your distribution is probably corrupt."
	@echo
