###############################################################################
# SPECtools2000
#   Version 0.3
#   This makefile should NOT be changed other than to customize for a 
#   particular benchmark.  Users may overide variables by placing them
#   in the Makefile.spec file.  Or by using the "runspec" program to 
#   build the Makefile.spec file for them.
###############################################################################
#	BENCHMARK	-- standard definitions for this benchmark

NUMBER    = 252
NAME      = eon
EXEBASE   = eon
BENCHLANG = CXX
SOURCES   =   \
    ggCoverageSolidTexture.cc \
    ggPathDielectricMaterial.cc \
    ggBox2.cc \
    ggBox3.cc \
    ggRasterSurfaceTexture.cc \
    ggJitterSample1.cc \
    ggNRooksSample2.cc \
    ggJitterSample2.cc \
    ggRGBFPixel.cc \
    ggRotatingPinholeCamera.cc \
    ggRandomSample2.cc \
    ggRandomSample3.cc \
    ggSolidNoise2.cc \
    ggSolidNoise3.cc \
    ggSolidTexture.cc \
    ggOakSolidTexture.cc \
    ggSpecularMaterial.cc \
    ggNA.cc \
    ggMaterial.cc \
    ggDiffuseMaterial.cc \
    ggDielectricMaterial.cc \
    ggConductorMaterial.cc \
    ggEdgeDiscrepancy.cc \
    ggPolishedMaterial.cc \
    ggFrameInterpolation.cc \
    ggQuaternion.cc \
    ggSpline.cc \
    ggONB2.cc \
    ggONB3.cc \
    ggFrame2.cc \
    ggFrame3.cc \
    ggHMatrix3.cc \
    ggSphere.cc \
    ggRGBE.cc \
    ggGamma.cc \
    ggBRDF.cc \
    ggDiffuseBRDF.cc \
    ggPhongBRDF.cc \
    ggPolishedBRDF.cc \
    ggCamera.cc \
    ggPinholeCamera.cc \
    ggThinLensCamera.cc \
    ggErr.cc \
    ggPixelFilter.cc \
    ggTrianglePixelFilter.cc \
    ggBoxPixelFilter.cc \
    ggFormat.cc \
    ggGeometry.cc \
    ggHAffineMatrix3.cc \
    ggHShearMatrix3.cc \
    ggHBoxMatrix3.cc \
    ggHPerspectiveMatrix3.cc \
    ggHTranslationMatrix3.cc \
    ggHRigidBodyMatrix3.cc \
    ggHRotationMatrix3.cc \
    ggHScaleMatrix3.cc \
    ggHPoint3.cc \
    ggPoint2.cc \
    ggPoint3.cc \
    ggOptics.cc \
    ggPlane.cc \
    ggPolygon.cc \
    ggGrayPixel_x.cc \
    ggRGBPixel_x.cc \
    ggRay2.cc \
    ggRay3.cc \
    ggBoardFloorSolidTexture.cc \
    ggVector2.cc \
    ggVector3.cc \
    ggString.cc \
    ggFineSpectrum.cc \
    ggSpectrum.cc \
    eon.cc \
    eonImageCalculator.cc \
    mrObjectRecord.cc \
    mrCoarsePixelRenderer.cc \
    mrIndirectPixelRenderer.cc \
    mrRushmeierPixelRenderer.cc \
    mrBruteForcePixelRenderer.cc \
    mrKajiyaPixelRenderer.cc \
    mrCookPixelRenderer.cc \
    mrGrid.cc \
    mrScene.cc \
    mrCamera.cc \
    mrTriangle.cc \
    mrFastTriangle.cc \
    mrPolygon.cc \
    mrXYDisk.cc \
    mrXZDisk.cc \
    mrYZDisk.cc \
    mrPhongAreaXYRectangleLuminaire.cc \
    mrPhongAreaXZRectangleLuminaire.cc \
    mrPhongAreaYZRectangleLuminaire.cc \
    mrEmitter.cc \
    mrImposter.cc \
    mrLinkedObjects.cc \
    mrBox.cc \
    mrXCylinder.cc \
    mrYCylinder.cc \
    mrZCylinder.cc \
    mrDiffuseAreaZCylinderLuminaire.cc \
    mrDiffuseCosineZCylinderLuminaire.cc \
    mrDiffuseVisibleAreaZCylinderLuminaire.cc \
    mrXEllipticalCylinder.cc \
    mrYEllipticalCylinder.cc \
    mrZEllipticalCylinder.cc \
    mrSpotAreaXYDiskLuminaire.cc \
    mrDiffuseAreaXYRectangleLuminaire.cc \
    mrDiffuseAreaXZRectangleLuminaire.cc \
    mrDiffuseAreaYZRectangleLuminaire.cc \
    mrSurfaceList.cc \
    mrDiffuseAreaTriangleLuminaire.cc \
    mrDiffuseAreaSphereLuminaire.cc \
    mrDiffuseCosineSphereLuminaire.cc \
    mrDiffuseSolidAngleSphereLuminaire.cc \
    mrShellLuminaire.cc \
    mrInstance.cc \
    mrMaterial.cc \
    mrPhongAreaTriangleLuminaire.cc \
    mrSolidTexture.cc \
    mrSphere.cc \
    mrSurface.cc \
    mrSurfaceTexture.cc \
    mrXYRectangle.cc \
    mrXZRectangle.cc \
    mrYZRectangle.cc \
    myrand.cc

# The following commented-out sources are included from .h files, but
# never built by themselves.
#    ggRaster.cc \
#    ggTrain.cc \
#    ggBST.cc \
#    ggIO.cc \
#    ggStaticArray.cc \
#    ggRGBPixel.cc \
#    ggPermute.cc \

# Include standard template for this suite
-include ../../../../Makefile.defaults
-include ../../../Makefile.defaults
-include ../../Makefile.defaults
-include ../Makefile.defaults

nomakefiles:
	@echo "*** Whoops!  I didn't find a Makefile.defaults file."
	@echo "*** Your distribution is probably corrupt."
	@echo
